platform :ios,'8.0'
use_frameworks!

target 'MeiLe_Click_Simplify' do
   
    pod 'AFNetworking', '~> 3.1.0'
    pod 'YYModel'
    pod 'SVProgressHUD'
    pod 'EAIntroView'
    pod 'BaiduMapKit'

end
